image: gitpod/workspace-full

tasks:
  - init: |
      sudo apt update
      sudo apt install openjdk-8-jdk -y
      wget https://downloads.apache.org/hadoop/common/hadoop-3.3.6/hadoop-3.3.6.tar.gz
      tar -xzf hadoop-3.3.6.tar.gz
      mv hadoop-3.3.6 hadoop
      echo 'export HADOOP_HOME=/workspace/hadoop' >> ~/.bashrc
      echo 'export PATH=$PATH:$HADOOP_HOME/bin' >> ~/.bashrc
      echo 'export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64' >> ~/.bashrc
      source ~/.bashrc
